<a href="https://colab.research.google.com/github/Shamshair-Ali007/AI/blob/main/sign_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!touch train_data.npy
!sudo apt-get install unzip
!unzip /content/drive/MyDrive/archive.zip

Streaming output truncated to the last 5000 lines.
  inflating: Sign Language for Alphabets/w/w_549.jpg  
  inflating: Sign Language for Alphabets/w/w_55.jpg  
  inflating: Sign Language for Alphabets/w/w_550.jpg  
  inflating: Sign Language for Alphabets/w/w_551.jpg  
  inflating: Sign Language for Alphabets/w/w_552.jpg  
  inflating: Sign Language for Alphabets/w/w_553.jpg  
  inflating: Sign Language for Alphabets/w/w_554.jpg  
  inflating: Sign Language for Alphabets/w/w_555.jpg  
  inflating: Sign Language for Alphabets/w/w_556.jpg  
  inflating: Sign Language for Alphabets/w/w_557.jpg  
  inflating: Sign Language for Alphabets/w/w_558.jpg  
  inflating: Sign Language for Alphabets/w/w_559.jpg  
  inflating: Sign Language for Alphabets/w/w_56.jpg  
  inflating: Sign Language for Alphabets/w/w_560.jpg  
  inflating: Sign Language for Alphabets/w/w_561.jpg  
  inflating: Sign Language for Alphabets/w/w_562.jpg  
  inflating: Sign Language for Alphabets/w/w_563.jpg  
  inflating: Sig

In [2]:
import cv2                 # working with, mainly resizing, images
import numpy as np         # dealing with arrays
import os                  # dealing with directories
from random import shuffle # mixing up or currently ordered data that might lead our network astray in training.

path='/content/Sign'

IMG_SIZE = 96

def create_train_data():
    training_data = []
    label=0
    for (dirpath,dirnames,filenames) in os.walk(path):
        for dirname in dirnames:
            print(dirname)
            for(direcpath,direcnames,files) in os.walk(path+"/"+dirname):
                for file in files:
                        actual_path=path+"/"+dirname+"/"+file
                        print(files)
                        # label=label_img(dirname)
                        path1 =path+"/"+dirname+'/'+file
                        img=cv2.imread(path1,cv2.IMREAD_GRAYSCALE)
                        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
                        training_data.append([np.array(img),label])
            label=label+1
            print(label)
    shuffle(training_data)
    np.save('/content/train_data.npy', training_data)
    print(training_data)
    return training_data

create_train_data()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



['o_1186.jpg', 'o_944.jpg', 'o_1257.jpg', 'o_1183.jpg', 'o_1067.jpg', 'o_1381.jpg', 'o_682.jpg', 'o_259.jpg', 'o_528.jpg', 'o_875.jpg', 'o_616.jpg', 'o_1363.jpg', 'o_1434.jpg', 'o_509.jpg', 'o_332.jpg', 'o_908.jpg', 'o_1357.jpg', 'o_1180.jpg', 'o_893.jpg', 'o_453.jpg', 'o_1010.jpg', 'o_913.jpg', 'o_215.jpg', 'o_915.jpg', 'o_1091.jpg', 'o_1491.jpg', 'o_1108.jpg', 'o_339.jpg', 'o_1190.jpg', 'o_716.jpg', 'o_119.jpg', 'o_782.jpg', 'o_630.jpg', 'o_927.jpg', 'o_1281.jpg', 'o_51.jpg', 'o_903.jpg', 'o_1417.jpg', 'o_12.jpg', 'o_29.jpg', 'o_1283.jpg', 'o_266.jpg', 'o_1030.jpg', 'o_1195.jpg', 'o_1232.jpg', 'o_779.jpg', 'o_375.jpg', 'o_670.jpg', 'o_1241.jpg', 'o_752.jpg', 'o_697.jpg', 'o_1126.jpg', 'o_996.jpg', 'o_1367.jpg', 'o_931.jpg', 'o_47.jpg', 'o_1373.jpg', 'o_725.jpg', 'o_255.jpg', 'o_745.jpg', 'o_115.jpg', 'o_238.jpg', 'o_860.jpg', 'o_883.jpg', 'o_627.jpg', 'o_369.jpg', 'o_186.jpg', 'o_536.jpg', 'o_1103.jpg', 'o_765.jpg', 'o_135.jpg', 'o_1136.jpg', 'o_122.jpg', 'o_1125.jpg', 'o_94.jpg', 'o

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



['v_980.jpg', 'v_891.jpg', 'v_1252.jpg', 'v_1183.jpg', 'v_447.jpg', 'v_1360.jpg', 'v_1383.jpg', 'v_859.jpg', 'v_618.jpg', 'v_784.jpg', 'v_604.jpg', 'v_920.jpg', 'v_441.jpg', 'v_945.jpg', 'v_1032.jpg', 'v_743.jpg', 'v_531.jpg', 'v_530.jpg', 'v_176.jpg', 'v_1296.jpg', 'v_1275.jpg', 'v_290.jpg', 'v_1074.jpg', 'v_50.jpg', 'v_999.jpg', 'v_559.jpg', 'v_96.jpg', 'v_1306.jpg', 'v_563.jpg', 'v_1225.jpg', 'v_1093.jpg', 'v_187.jpg', 'v_1500.jpg', 'v_298.jpg', 'v_725.jpg', 'v_1410.jpg', 'v_1138.jpg', 'v_1114.jpg', 'v_506.jpg', 'v_1487.jpg', 'v_1208.jpg', 'v_393.jpg', 'v_255.jpg', 'v_445.jpg', 'v_1401.jpg', 'v_1353.jpg', 'v_1189.jpg', 'v_1481.jpg', 'v_1033.jpg', 'v_205.jpg', 'v_368.jpg', 'v_688.jpg', 'v_996.jpg', 'v_818.jpg', 'v_865.jpg', 'v_481.jpg', 'v_1221.jpg', 'v_1086.jpg', 'v_774.jpg', 'v_148.jpg', 'v_149.jpg', 'v_1316.jpg', 'v_643.jpg', 'v_1148.jpg', 'v_642.jpg', 'v_1291.jpg', 'v_433.jpg', 'v_664.jpg', 'v_1477.jpg', 'v_1026.jpg', 'v_701.jpg', 'v_1370.jpg', 'v_1090.jpg', 'v_12.jpg', 'v_716.jp

/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[[array([[ 87,  92,  93, ...,  85,  82,  79],
         [ 86,  91,  93, ...,  86,  84,  81],
         [ 85,  89,  91, ...,  88,  86,  83],
         ...,
         [171, 172, 175, ..., 149, 145, 144],
         [170, 172, 175, ..., 148, 145, 144],
         [171, 173, 174, ..., 147, 144, 143]], dtype=uint8), 17],
 [array([[157, 155, 153, ...,  98,  97,  98],
         [156, 154, 153, ...,  99,  98,  99],
         [156, 154, 153, ..., 100, 100, 100],
         ...,
         [128, 127, 125, ..., 103, 107, 111],
         [128, 126, 125, ..., 104, 108, 112],
         [128, 126, 125, ..., 105, 109, 113]], dtype=uint8), 6],
 [array([[ 1,  5, 81, ...,  0,  0,  0],
         [ 1,  6, 83, ...,  0,  0,  0],
         [ 0,  8, 86, ...,  0,  0,  1],
         ...,
         [ 0,  0,  0, ..., 89,  8,  1],
         [ 0,  0,  0, ..., 88,  7,  0],
         [ 0,  0,  0, ..., 88,  6,  0]], dtype=uint8), 8],
 [array([[103, 105, 106, ..., 132, 138, 143],
         [103, 105, 106, ..., 132, 138, 142],
         [103, 1

In [3]:
!pip install tflearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 107 kB 4.8 MB/s 
  Created wheel for tflearn: filename=tflearn-0.5.0-py3-none-any.whl size=127299 sha256=88c62cb0f27083c83feb60c828714b52264a774c759769db1c2cc6a41edd8db8
  Stored in directory: /root/.cache/pip/wheels/5f/14/2e/1d8e28cc47a5a931a2fb82438c9e37ef9246cc6a3774520271
Successfully built tflearn


In [4]:
# dealing with directories

import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

IMG_SIZE = 96
LR = 1e-3

nb_classes=28

MODEL_NAME = 'handsign.model'

def cnn_model():
	convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

	convnet = conv_2d(convnet, 8, 5, activation='relu')
	convnet = max_pool_2d(convnet, 5)

	convnet = conv_2d(convnet, 16, 5, activation='relu')
	convnet = max_pool_2d(convnet, 5)

	convnet = conv_2d(convnet, 32, 5, activation='relu')
	convnet = max_pool_2d(convnet, 5)

	convnet = conv_2d(convnet, 64, 5, activation='relu')
	convnet = max_pool_2d(convnet, 5)

	convnet = conv_2d(convnet, 128, 5, activation='relu')
	convnet = max_pool_2d(convnet, 5)

	convnet = fully_connected(convnet, 1024, activation='relu')
	convnet = dropout(convnet, 0.8)

	convnet = fully_connected(convnet, nb_classes, activation='softmax')
	convnet = regression(convnet, optimizer='adam', learning_rate=0.01, loss='categorical_crossentropy', name='targets')

	model = tflearn.DNN(convnet, tensorboard_dir='log')
	
	return model




Instructions for updating:
non-resource variables are not supported in the long term


In [6]:

import cv2                 # working with, mainly resizing, images
import numpy as np         # dealing with arrays
import os                  # dealing with directories

import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression
# import cnn_sgn

IMG_SIZE = 96
LR = 0.1  #.001 learing rate

nb_classes=28

MODEL_NAME = 'handsign.model'

def one_hot_targets_(labels_dense,nb_classes):
    targets = np.array(Y).reshape(-1)
    print(targets)
    one_hot_targets = np.eye(nb_classes)[targets]
    return one_hot_targets


train_data = np.load('train_data.npy',encoding="latin1", allow_pickle=True)
# test_data = np.load('test_data.npy',encoding="latin1")

train = train_data[:]
test = train_data[:100]

print('traindatlen:'+str(len(train)))
print('testdatalen:'+str(len(test)))

X = np.array([i[0] for i in train]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
Y = [i[1] for i in train]
Y1=one_hot_targets_(Y,nb_classes)
# 
# print('max y'+str(max(Y)))
# print('min y'+str(min(Y)))
print('val y'+str(Y1))
print('len X:'+str(len(X)))
print('len Y:'+str(len(Y)))
test_x = np.array([i[0] for i in test]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
test_y = [i[1] for i in test]
test_y1=one_hot_targets_(test_y,nb_classes)
test_y=test_y1
Y=Y1
print('test_x:'+str(len(test_x)))
print('test_y:'+str(len(test_y)))
print('val y'+str(test_y1))

model=cnn_model()
# print(model)
model.fit({'input': X}, {'targets': Y}, n_epoch=20, validation_set=({'input': test_x}, {'targets': test_y}), 
snapshot_step=500, show_metric=True, run_id=MODEL_NAME)

# model.fit({'input': X}, {'targets': Y}, n_epoch=15, validation_set=({'input': test_x}, {'targets': test_y}), snapshot_step=500, show_metric=True, run_id=MODEL_NAME)

model.save(MODEL_NAME)



score = model.evaluate(test_x, test_y)
print('Test accuarcy: %0.4f%%' % (score[0] * 100))

traindatlen:40500
testdatalen:100
[17  6  8 ... 10 24 20]
val y[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
len X:40500
len Y:40500
[17  6  8 ... 10 24 20]
test_x:100
test_y:40500
val y[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---------------------------------
Run id: handsign.model
Log directory: log/
---------------------------------
Training samples: 81000
Validation samples: 200
--


InvalidArgumentError: ignored